apiVersion: apps/v1
kind: Deployment

metadata:
  name: return-db
  namespace: intelligent-supply-chain

spec:
  replicas: 1

  selector:
    matchLabels:
      app: return-db

  template:

    metadata:
      labels:
        app: return-db

    spec:

      containers:

        - name: return-db

          image: postgres:16

          ports:
            - containerPort: 5432

          env:

            - name: POSTGRES_DB
              value: supply_returndb

            - name: POSTGRES_USER
              value: postgres

            - name: POSTGRES_PASSWORD
              value: postgres

---
apiVersion: v1
kind: Service

metadata:
  name: return-db
  namespace: intelligent-supply-chain

spec:

  selector:
    app: return-db

  ports:
    - port: 5432
      targetPort: 5432

  type: ClusterIP